### ISSUE TITLE
EGIG expedition profiles

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#26]
## Data source (PDF)

> Brockamp, B. (1965). Über einige geophysikalische Ergebnisse der internationalen Grönland-Expedition EGIG 1959. Polarforschung, 35(1/2), 42-66.

+ PDF: [Polarforsch1965_1-2_8.pdf](https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/files/7185520/Polarforsch1965_1-2_8.pdf)

The PDF linked above has a wealth of data. I pull out some of the graphics into this issue here as PNGs:

### Map

![image](https://user-images.githubusercontent.com/145117/133782429-fe556db9-a5f2-49ec-9875-6e95eb7ad0c1.png)

### Temperature profiles

![image](https://user-images.githubusercontent.com/145117/133782613-f29b1d7e-1370-4144-af79-4e8ffd354c90.png)

Zooming in on the top axis, it is difficult to see borehole labels:

![image](https://user-images.githubusercontent.com/145117/133782766-2d170f47-755f-45b4-b521-205005e3e0d8.png)

## Questions

+ [ ] All profiles appear 2x, starting near the same temperature and deviating at depth. Why? Which should we use?
+ [ ] On p. 58 there is mention of `Camp VI EPF` **and** `Camp VI EPF`, but there is no other mention of `IV` in the document. In thefigure, `CVI EPF` and `CVI EGIG` appear 2x. Is it possible there is a typo and one of these profiles is `VI and one is `VI`? Which is which?
+ [ ] `P.N.` is Punkt. Nord from p. 53 of the above document.
+ [ ] `Mc.` is Milcent from p. 53. - Closes #5 
+ [ ] `Site II` is already in our DB. See https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/tree/main/SiteII
+ [ ] `St. C.` is Station Centrale from p. 53 - Closes #9 
+ [ ] `Cr` is Crête from p. 53 - Closes #4 
+ [ ] `J. J.` is Jarl Joset from p. 53

## End

+ @BaptisteVandecrux : Some new firn profiles here if you have not seen this document? See also 3 boreholes at #25

**Comment by mankoff** [comment]
From translation (thanks to M. Lüthi) we only digitize `+` symbols: StationCentrale_EGIG, SiteII_EGIG, and CVI_EPF. These may be duplicates from Heuberger (1954) but are still useful at this point to digitize for quality control on the digitization process.

The above figure has all data on 10 m intervals, so even the Y axis (depth) from the digitization provides useful information about precision and accuracy.

**Comment by mankoff** [comment]
Closed in #8ad192b.
